require('dotenv').config();
const { supabase } = require('./supabaseClient');

async function setupTable() {
  console.log("To set up your table, please run this SQL in your Supabase SQL Editor:");
  console.log(`
    CREATE TABLE bot_responses (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      keyword TEXT UNIQUE NOT NULL,
      response TEXT NOT NULL,
      created_at TIMESTAMPTZ DEFAULT NOW()
    );

    -- Insert some sample data
    INSERT INTO bot_responses (keyword, response) VALUES 
    ('hello', 'Hi there! How can I help you today?'),
    ('hours', 'We are open from 9 AM to 6 PM.'),
    ('location', 'You can find us at 123 Main Street.');
  `);
}

setupTable();
